import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {transform} from 'esbuild';
async function module(path){const {code}=await transform(await readFile(path,'utf8'),{loader:'ts',format:'esm'});return import('data:text/javascript;base64,'+Buffer.from(code).toString('base64'));}
const {resultFor}=await module('lib/grading.ts');
const {quote,profit,games}=await module('lib/basketball.ts');
assert.equal(profit(10,-110),9.09);assert.equal(profit(10,155),15.5);assert.equal(profit(1,-185),.54);
assert.equal(resultFor('moneyline',0,null,100,101),'lost');
assert.equal(resultFor('moneyline',1,null,100,101),'won');
assert.equal(resultFor('spread',0,4,100,104),'push');
assert.equal(resultFor('spread',1,-4,100,104),'push');
assert.equal(resultFor('spread',0,4.5,100,104),'won');
assert.equal(resultFor('total',0,204,100,104),'push');
assert.equal(resultFor('total',1,204,100,104),'push');
assert.equal(resultFor('total',1,203.5,100,104),'lost');
assert.equal(quote(games[0],'spread',0).point,-4.5);
const {parseOdds}=await module('lib/espn.ts');
const row=(code,spread,total,ml)=>({line:{primaryText:code,primaryTextFullWide:code},pointSpread:{primary:spread,secondary:'-110'},total:{primary:total,secondary:'-110'},moneyline:{primary:ml}});
const fixture={page:{content:{odds:{odds:[{sections:[{games:[{date:'2099-01-01T20:00Z',timeValid:true,isLiveState:false,gameInfo:{gameId:'123'},providerName:'draftkings',odds:[row('BOS','+1.5','o220.5','+105'),row('DET','-1.5','u220.5','-125')]}]}]}]}}}};
const html=()=>`window['__espnfitt__']=${JSON.stringify(fixture)};`;
assert.equal(parseOdds(html()).length,1);
fixture.page.content.odds.odds[0].sections[0].games[0].odds[0].moneyline.primary='OFF';assert.equal(parseOdds(html()).length,0);
assert.throws(()=>parseOdds('<html>unavailable</html>'));
console.log('PASS: American odds, spread signs, both sides, pushes, totals, ESPN parser and fail-closed source validation.');
const {combinedDecimal,americanOdds,parlayProfitCents,gradeParlay}=await module('lib/parlay.ts');
assert.equal(americanOdds(combinedDecimal([-110,-110])),264);
assert.equal(parlayProfitCents(1000,[-110,-110]),2645);
assert.equal(parlayProfitCents(1000,[150,-200]),2750);
const legs=(...results)=>results.map(result=>({odds:-110,result}));
assert.deepEqual(gradeParlay(1000,legs('won','won')),{result:'won',profitCents:2645});
assert.equal(gradeParlay(1000,legs('won','pending')).result,'pending');
assert.deepEqual(gradeParlay(1000,legs('lost','pending')),{result:'lost',profitCents:0});
assert.deepEqual(gradeParlay(1000,legs('won','push','void')),{result:'won',profitCents:909});
assert.deepEqual(gradeParlay(1000,legs('push','void')),{result:'push',profitCents:0});
assert.deepEqual(gradeParlay(1000,legs('push','pending')),{result:'pending',profitCents:909});
console.log('PASS: combined parlay pricing, cent rounding, pending/loss/win settlement, push and void recalculation, full refund.');
